# Generated by Django 5.0.4 on 2025-03-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modifica'),
        ),
    ]
